# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# Ignore maximize requests from apps. You'll probably like this.

windowrule {
    name = greedyApps
    suppress_event = maximize
    match:class = .*
}

# Fix some dragging issues with XWayland

windowrule {
    name = xWaylandFix
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    float = 1
    fullscreen = 0
    match:pin = 0
}

#BlueTooth Manager_OverSkride

windowrule {
    name = init_OverSkride
    match:class = io.github.kaii_lb.Overskride
    float = 1
    center = 1
}

#Steam

windowrule {
    name = init_SteamFloat
    match:class = ^(steam)$
    match:title = ^(Friends List)$
    size = 500 700
    float = 1
    center = 1
}

#Picture in Picture

windowrule {
    name = init_PicInPic
    match:title = Picture-in-Picture
    match:title = Picture-in-Picture
    float = 1
    pin = 1
    rounding = 0
    opaque = 1
}

#Waypaper

windowrule {
    name = init_waypaper
    match:class = waypaper
    size = 1200 900
    float = 1
}

#BlenderLaunucher

windowrule {
    name = init_BlenderLauncher
    match:class = blenderlauncher
    size = 1280 720
    float = 1
    center = 1
}

#MPV

windowrule {
    name = init_mpv
    match:class = mpv
    float = 1
    center = 1
}


layerrule {
    name = disable_quickshell_animations
    match:namespace = quickshell
    no_anim = on
}
